# https://github.com/ashishb/dotfiles/blob/master/.travis.yml

branches:
  except:
    - dev

# https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages
# Test on Both GNU/Linux and Mac OS
matrix:
  include:
    - name: Test on ubuntu
      os: linux
      dist: trusty
      sudo: false
      script:
        - bash install ubuntu.mk
    - name: Test on ubuntu 18.04
      os: linux
      dist: bionic
      sudo: false
      script:
        - bash install ubuntu.mk
    - name: Test on Mac OS X
      os: osx
      osx_image: xcode11.3
      sudo: required
      script:
        - bash install mac.mk
    - name: Test on windows
      os: windows
      script:
        - bash install mac.mk
