# https://github.com/ashishb/dotfiles/blob/master/.travis.yml
# https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages

branches:
  except:
    - dev

matrix:
  include:
    - name: Ubuntu18.04
      os: linux
      dist: bionic
      sudo: false
      script:
        - bash install.sh
    - name: Test on Mac OS X
      os: osx
      osx_image: xcode11.3
      sudo: required
      script:
        - bash install.sh
    - name: Test on windows
      os: windows
      script:
        - bash install.sh
