add_new_line = false

[line_break]
disabled = true

[package]
disabled = true

[python]
disabled = true

[ruby]
disabled = true

[nodejs]
disabled = true

[java]
disabled = true

[golang]
disabled = true

[aws]
disabled = true
