#!/bin/sh

sxhkd &	
# xmodmap -e "keycode 47 = colon semicolon" # remap : and ;

export EDITOR="nvim"
export TERMINAL="kitty"
export BROWSER="chromium"
export READER="zathura"
export FILE="lf"

# xrandr --output eDP-1 --mode 2560x1440
# xrandr --output eDP-1 --mode 3200x1800
# mons -e right
# mons -O 2

setxkbmap -layout us &
mons -S 3,2:R &
setbg &
dwmblocks &

# clipmenud &
# dunst &
# davmail &
# nmcli con up vpno 2>&1 &
# megasync &
# pcloud &
# nextcloud &
# dwmstatus 2>&1
# redshift -P -O 2000 &
# megasync &
# davmail &


xset r rate 300 50 # Speed xrate up
setxkbmap -option ctrl:nocaps # CapsLock behaves like Ctrl
xcape -e 'Control_L=Escape' # short-pressed Ctrl behaves like Escape
