#!/bin/sh

sxhkd &	# Bind keys
xset r rate 300 50 &	# Speed xrate up

# make CapsLock behave like Ctrl:
setxkbmap -option ctrl:nocaps
# xmodmap -e "keycode 47 = colon semicolon" # remap : and ;

# make short-pressed Ctrl behave like Escape:
xcape -e 'Control_L=Escape'

# VPN
# nmcli con up vpn 2>&1

# Monitor
# xrandr --output eDP-1 --mode 2560x1440
# xrandr --output eDP-1 --mode 3200x1800
# mons -e right
mons -O 2

dunst &
# davmail &
# nmcli con up vpno 2>&1 &
# megasync &
# pcloud &
# nextcloud &
# dwmstatus 2>&1
# redshift -P -O 2000 &
# megasync &
# davmail &
setbg &
dwmblocks &

