# ##############################################################
# This configuration file lets you
# - define new commands
# - change the shortcut or triggering keys of built-in verbs
# - change the colors
# - set default values for flags
#
# Configuration documentation is available at
# https://dystroy.org/broot
# ##############################################################

# ##############################################################
# Default flags
# You can set up flags you want broot to start with by
# default, for example `default_flags="ihp"` if you usually want
# to see hidden and gitignored files and the permissions (then
# if you don't want the hidden files you can launch `br -H`
#
default_flags = ""

# If $EDITOR isn't set on your computer, you should either set it using
# something similar to
# export EDITOR=/usr/bin/nvim
# or just replace it with your editor of choice in the 'execution'
# pattern.
# Example:
# execution = "/usr/bin/nvim {file}"
#
[[verbs]]
execution = "$EDITOR {file}"
invocation = "edit"
key = "F2"
shortcut = "e"

[[verbs]]
execution = ":quit"
key = "ctrl-c"

[[verbs]]
execution = "$EDITOR {directory}/{subpath}"
invocation = "create {subpath}"

[[verbs]]
execution = ":toggle_git_file_info"
key = "ctrl-s"

[[verbs]]
execution = "$PAGER {file}"
invocation = "view"
name = "view"

[[verbs]]
execution = ":parent"
key = "left"

[[verbs]]
execution = ":focus"
key = "right"

[[verbs]]
execution = ":parent"
key = "ctrl-h"

[[verbs]]
execution = ":focus"
key = "ctrl-l"

[[verbs]]
execution = ":line_down"
key = "ctrl-j"

[[verbs]]
execution = ":line_up"
key = "ctrl-k"

[[verbs]]
execution = ":page_down"
key = "ctrl-d"

[[verbs]]
# [skin]
default = "rgb(25, 25, 25)"
execution = ":page_up"
key = "ctrl-u"

# You may find other skins on
# https://dystroy.org/broot/documentation/configuration/#colors
# for example a skin suitable for white backgrounds
